res/throwaway_domains.txt
Please add `fake-box.com` to the disposal emails list.
=> Hotfix : `fake-box.com` added to res/throwaway_domains.txt

res/throwaway_domains.txt
Mail.ru is the largest mail service in Russia, it's definitely not a throwaway domain.
=> removed mail.ru from the database

res/throwaway_domains.txt
trbvn.com is used by 10minutemail.com, and the other domains are used by temp-mail.org
=> Added more throwaway domains.

res/throwaway_domains.txt
Onet.pl is definitely not disposable mailbox.
=> Removed false positive

src/EmailChecker/Laravel/EmailCheckerServiceProvider.php
Deferring the provider registration means the custom validation rule never gets registered unless the class has already been resolved from the service container.
=> Don't defer the Laravel provider. Closes #26.

res/throwaway_domains.txt
I was unable to track which service offers 2emea.com but it does appear to be a disposable email domain. Ref: https://www.stopforumspam.com/domain/2emea.com
=> Add email domains from tempail.com and temporaryemail.org

composer.json
Laravel 5.5 supports package auto-discovery, so editing the `config/app.php` becomes obsolete. 
Here I add the needed configurations to enable Laravel to find this package.
https://laravel.com/docs/5.5/packages#package-discovery
=> Add support for Laravel 5.5 package auto discovery

.travis.yml, composer.json, tests/EmailChecker/Tests/Adpater/AgregatorAdapterTest.php, tests/EmailChecker/Tests/Adpater/ArrayAdapterTest.php, tests/EmailChecker/Tests/Adpater/BuiltInAdapterTest.php, tests/EmailChecker/Tests/Adpater/FileAdapterTest.php, tests/EmailChecker/Tests/Adpater/GaufretteAdapterTest.php, tests/EmailChecker/Tests/Constraint/NotThrowawayEmailValidatorTest.php, tests/EmailChecker/Tests/EmailCheckerTest.php, tests/EmailChecker/Tests/TestCase.php
This PR will add compatibility with PHP 8.
Unfortunately, I have to drop some supported PHP versions.
PHP 8 is strict about return types which were introduced in PHP 7, so I have to drop support for PHP 5.4-5.6.
`void `return type (now required in PHPUnit) was introduced in PHP 7.1, so I have to drop support for PHP 7.0
=> Add compatibility with PHP 8

res/throwaway_domains.txt
According to wiki and other resources, naver.co is a large South Korean search engine and proper mail provider. Hence it should not be black-listed.
=> Remove naver.com from the throwaway domains

res/throwaway_domains.txt
Update ths list according to gist.github.com/michenriksen/8710649#.
QQ.com is a domain owned by the Tencent, so it was removed.
Also, some domains were added from sites like temp-mail.org or mohmail.com#.
=> Update disponsable domain list

composer.json, src/EmailChecker/Laravel/EmailCheckerServiceProvider.php
This PR aim to fix class resolution issues by adding the missing `illuminate/support` composer dependency.
Also, the `Validator` alias was replaced with its facade. Aliases can be replaced or removed in the app configuration, therefore they should never be used in a library.
=> Add missing composer dependency

.travis.yml, src/EmailChecker/ThrowawayDomains.php
This PR is to fix deprecation messages on PHP 8.1:
```
PHP Deprecated:  Return type of EmailChecker\ThrowawayDomains::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/src/EmailChecker/ThrowawayDomains.php on line 33
PHP Deprecated:  Return type of EmailChecker\ThrowawayDomains::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/src/EmailChecker/ThrowawayDomains.php on line 38
```
=> Add compatibility with PHP 8.1

src/EmailChecker/Laravel/EmailCheckerServiceProvider.php, src/EmailChecker/ThrowawayDomains.php
Hi @MattKetmo, I tried to use your library and got deprecations messages like
```
Deprecated: Creation of dynamic property EmailChecker\ThrowawayDomains::$domains is deprecated in mattketmo/email-checker/src/EmailChecker/ThrowawayDomains.php on line 23
```
I look for all the dynamic properties in the code and fixed them in this PR.
If you find time to review/merge/release this, this would be awesome.
Thanks.
=> Solve deprecation for php 8.2

.gitattributes
Hi @MattKetmo,
The gitattributes file was excluding test folder, but this folder is called tests.
=> Fix .gitattributes about tests folder

src/EmailChecker/Constraints/NotThrowawayEmail.php
Hi @MattKetmo
Symfony constraints can be used as attribute for PHP8
https://symfony.com/blog/new-in-symfony-5-2-constraints-as-php-attributes
This PR allow the same for the EmailChecker constraint.
=> Allow to use constraint as attribute

src/EmailChecker/Constraints/NotThrowawayEmail.php
Hi @MattKetmo 
This allows to write
```
#[NotThrowawayEmail(message: 'user.message.error.invalid_email_domain')]
```
when using the constraint as an attribute.
This is similar to Symfony constraint: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Validator/Constraints/Email.php#L48
=> Allow to override message when using attributes

res/throwaway_domains.txt
Following domains are added (based on the alphabetical order of the file) and they can be tested [here](https://verifymail.io/domain/funnymail.de) or [here](https://www.mailboxvalidator.com/domain#result) for example
- candymail.de
- doublemail.de
- funnymail.de
- nezid.com
- puppetmail.de
- spoofmail.es
- spoofmail.fr
Thank you in advance
=> adding a couple of domains

res/throwaway_domains.txt
This domain is offered by https://correotemporal.org/
=> Add domains offered by correotemporal.org

src/EmailChecker/Utilities.php
=> fix: ensure parse gets a valid email

src/EmailChecker/Constraints/NotThrowawayEmail.php, src/EmailChecker/Constraints/NotThrowawayEmailValidator.php, src/EmailChecker/EmailChecker.php
Hi @MattKetmo 
This lib has deprecations on php 8.4 like
```
EmailChecker\Constraints\NotThrowawayEmail::__construct(): Implicitly marking parameter $groups as nullable is deprecated, the explicit nullable type must be used instead.
EmailChecker\Constraints\NotThrowawayEmailValidator::__construct(): Implicitly marking parameter $emailChecker as nullable is deprecated, the explicit nullable type must be used instead.
EmailChecker\EmailChecker::__construct(): Implicitly marking parameter $adapter as nullable is deprecated, the explicit nullable type must be used instead.
```
=> Fix php 84 deprecations
